// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:0781718c-dcf1-40bd-be57-374a342f192b",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_7csL9jg4h",
    "aws_user_pools_web_client_id": "4i1i5clofgbs2nvmjvglfh53ru"
};


export default awsmobile;
